FROM qgis/qgis-server:ltr

COPY project.qgs /data/project.qgs
COPY data/ /data/
RUN chmod -R 777 /data

ENV QGIS_PROJECT_FILE=/data/project.qgs

# QGIS_SERVER_SERVICE_URL is set at runtime via .env / Railway / Fly variables
ENV QGIS_SERVER_SERVICE_URL=
EXPOSE 80
