name: Build and Publish GIS Images

on:
  push:
    branches:
      - main
      - unstable
      - "dev"
      - "feature/**"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: docker/pygeoapi
            tag: minimal
            target: minimal
          - context: docker/qgis
            tag: qgis
          - context: docker/worker
            tag: worker

    steps:
      - uses: actions/checkout@v4

      - name: Determine Image Repository
        id: repo_info
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == refs/heads/main ]] || [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "image_repo=waystones-keystone" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/unstable ]]; then
            echo "image_repo=waystones-shard" >> $GITHUB_OUTPUT
          else
            echo "image_repo=waystones-void" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Cloudflare Registry
        uses: docker/login-action@v3
        with:
          registry: deploy.cloudflare.com
          username: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          password: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Build and push ${{ matrix.tag }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.repo_info.outputs.image_repo }}:${{ matrix.tag }}-${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/${{ steps.repo_info.outputs.image_repo }}:${{ matrix.tag }}-latest
            deploy.cloudflare.com/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/${{ steps.repo_info.outputs.image_repo }}:${{ matrix.tag }}-latest
          target: ${{ matrix.target }}
          push: true
          cache-from: type=gha,scope=${{ matrix.tag }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag }}
