name: Build and Publish GIS Images

on:
  push:
    branches:
      - main
      - unstable
      - "dev"
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: docker/pygeoapi
            tag: minimal
            target: minimal
          - context: docker/qgis
            tag: qgis
          - context: docker/worker
            tag: worker

    steps:
      - uses: actions/checkout@v4

      - name: Determine Image Repository
        id: repo_info
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == refs/heads/main ]] || [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "image_repo=waystones-keystone" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/unstable ]]; then
            echo "image_repo=waystones-shard" >> $GITHUB_OUTPUT
          else
            echo "image_repo=waystones-void" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build local image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          tags: ${{ steps.repo_info.outputs.image_repo }}-${{ matrix.tag }}:v2026-05-04m
          target: ${{ matrix.target }}
          load: true
          push: false
          cache-from: type=gha,scope=${{ matrix.tag }}
          cache-to: type=gha,mode=max,scope=${{ matrix.tag }}

      - name: Push to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4"
          command: containers push ${{ steps.repo_info.outputs.image_repo }}-${{ matrix.tag }}:v2026-05-04m
